// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPSi3j5YTwztm01YJceCI1EM7hE5KA9AI',
    appId: '1:449901043836:web:f64253a59f1212be92a9f9',
    messagingSenderId: '449901043836',
    projectId: 'jc-sports-hub',
    authDomain: 'jc-sports-hub.firebaseapp.com',
    storageBucket: 'jc-sports-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7aQmq-lMPhwvjzWclAKnEBNR-2N4BGc',
    appId: '1:449901043836:android:e3949cee68d5393b92a9f9',
    messagingSenderId: '449901043836',
    projectId: 'jc-sports-hub',
    storageBucket: 'jc-sports-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEfD2L9WbRXInOEsLe2M8TVdbW6-FX0Es',
    appId: '1:449901043836:ios:3372655c6a97ab3c92a9f9',
    messagingSenderId: '449901043836',
    projectId: 'jc-sports-hub',
    storageBucket: 'jc-sports-hub.firebasestorage.app',
    iosBundleId: 'com.example.jcSportsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEfD2L9WbRXInOEsLe2M8TVdbW6-FX0Es',
    appId: '1:449901043836:ios:3372655c6a97ab3c92a9f9',
    messagingSenderId: '449901043836',
    projectId: 'jc-sports-hub',
    storageBucket: 'jc-sports-hub.firebasestorage.app',
    iosBundleId: 'com.example.jcSportsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPSi3j5YTwztm01YJceCI1EM7hE5KA9AI',
    appId: '1:449901043836:web:e8a88d3e2616cb1492a9f9',
    messagingSenderId: '449901043836',
    projectId: 'jc-sports-hub',
    authDomain: 'jc-sports-hub.firebaseapp.com',
    storageBucket: 'jc-sports-hub.firebasestorage.app',
  );
}
